Don't nest <pre> and <code>in Javadoc
Javadoc (Java 8 onwards?) complains if you wrap <pre> within <code>, or
<code> within <pre>. Produces for example:
error: block element not allowed within inline element <code>: pre

<pre> is normally sufficient on its own.

Although this doesn't currently affect this project, which is still
aiming for backward compatibility, fix for consistency with other
projects anyway.